networks:
    my_network:
        driver: bridge
services:
    mysql:
        image: mysql
        env_file:
            - .env
        ports:
            - "3306:3306"
        networks:
            - my_network

